### ISSUE TITLE
cargo run fails due to missing or private dependency repo

### ISSUE THREAD

**Issue by brabo** [Septias/deltachat-github-bot#5]
$ addr=ghbot@example.org mail_pw=sekrit cargo run
    Updating git repository `https://github.com/deltachat/deltachat-core-rust`
    Updating crates.io index
    Updating git repository `https://github.com/async-email/async-imap`
    Updating git repository `https://github.com/dignifiedquire/rs-async-zip`
    Updating git repository `https://github.com/deltachat/rust-email`
    Updating git repository `https://github.com/async-email/encoded-words`
    Updating git repository `https://github.com/deltachat/lettre`
    Updating git repository `https://github.com/Majored/rs-async-io-utilities`
error: failed to get `async_io_utilities` as a dependency of package `async_zip v0.0.8 (https://github.com/dignifiedquire/rs-async-zip?branch=main#5556c5ac)`
    ... which satisfies git dependency `async_zip` (locked to 0.0.8) of package `deltachat v1.98.0 (https://github.com/deltachat/deltachat-core-rust?tag=1.98.0#b6b2f453)`
    ... which satisfies git dependency `deltachat` (locked to 1.98.0) of package `github-bot v0.1.0 (/home/ghbot/github-bot)`

Caused by:
  failed to load source for dependency `async_io_utilities`

Caused by:
  Unable to update https://github.com/Majored/rs-async-io-utilities#85de4cfc

Caused by:
  failed to clone into: /home/ghbot/.cargo/git/db/rs-async-io-utilities-5b754873e3909201

Caused by:
  failed to authenticate when downloading repository

  * attempted to find username/password via git's `credential.helper` support, but failed

  if the git CLI succeeds then `net.git-fetch-with-cli` may help here
  https://doc.rust-lang.org/cargo/reference/config.html#netgit-fetch-with-cli

Caused by:
  failed to acquire username/password from local configuration

**Comment by Septias** [comment]
The bot is not the problem actually, the missing dependency is from inside the deltachat-core package.

**Comment by Septias** [comment]
Tested it locally, but it works fine for me. Maybe try to `rustup update`?

**Comment by brabo** [comment]
$ sh rustup-init.sh -y
info: downloading installer
info: profile set to 'default'
info: default host triple is x86_64-unknown-linux-gnu
info: syncing channel updates for 'stable-x86_64-unknown-linux-gnu'
info: latest update on 2022-12-15, rust version 1.66.0 (69f9c33d7 2022-12-12)
info: downloading component 'cargo'
info: downloading component 'clippy'
info: downloading component 'rust-docs'
info: downloading component 'rust-std'
info: downloading component 'rustc'
info: downloading component 'rustfmt'
info: installing component 'cargo'
info: installing component 'clippy'
info: installing component 'rust-docs'
 19.0 MiB /  19.0 MiB (100 %)  14.3 MiB/s in  1s ETA:  0s
info: installing component 'rust-std'
 29.7 MiB /  29.7 MiB (100 %)  17.1 MiB/s in  1s ETA:  0s
info: installing component 'rustc'
 68.0 MiB /  68.0 MiB (100 %)  20.4 MiB/s in  3s ETA:  0s
info: installing component 'rustfmt'
info: default toolchain set to 'stable-x86_64-unknown-linux-gnu'

  stable-x86_64-unknown-linux-gnu installed - rustc 1.66.0 (69f9c33d7 2022-12-12)


Rust is installed now. Great!

To get started you may need to restart your current shell.
This would reload your PATH environment variable to include
Cargo's bin directory ($HOME/.cargo/bin).

To configure your current shell, run:
source "$HOME/.cargo/env"
ghbot@Debian-bullseye-latest-amd64-base:~$ source "$HOME/.cargo/env"
ghbot@Debian-bullseye-latest-amd64-base:~$ cd deltachat-github-bot/
ghbot@Debian-bullseye-latest-amd64-base:~/deltachat-github-bot$ addr=ghbot@example.org mail_pw=sekrit cargo run
    Updating git repository `https://github.com/deltachat/deltachat-core-rust`
    Updating crates.io index
    Updating git repository `https://github.com/async-email/async-imap`
    Updating git repository `https://github.com/dignifiedquire/rs-async-zip`
    Updating git repository `https://github.com/deltachat/rust-email`
    Updating git repository `https://github.com/async-email/encoded-words`
    Updating git repository `https://github.com/deltachat/lettre`
    Updating git repository `https://github.com/Majored/rs-async-io-utilities`
error: failed to get `async_io_utilities` as a dependency of package `async_zip v0.0.8 (https://github.com/dignifiedquire/rs-async-zip?branch=main#5556c5ac)`
    ... which satisfies git dependency `async_zip` (locked to 0.0.8) of package `deltachat v1.98.0 (https://github.com/deltachat/deltachat-core-rust?tag=1.98.0#b6b2f453)`
    ... which satisfies git dependency `deltachat` (locked to 1.98.0) of package `github-bot v0.1.0 (/home/ghbot/deltachat-github-bot)`

Caused by:
  failed to load source for dependency `async_io_utilities`

Caused by:
  Unable to update https://github.com/Majored/rs-async-io-utilities#85de4cfc

Caused by:
  failed to clone into: /home/ghbot/.cargo/git/db/rs-async-io-utilities-5b754873e3909201

Caused by:
  failed to authenticate when downloading repository

  * attempted to find username/password via git's `credential.helper` support, but failed

  if the git CLI succeeds then `net.git-fetch-with-cli` may help here
  https://doc.rust-lang.org/cargo/reference/config.html#netgit-fetch-with-cli

Caused by:
  failed to acquire username/password from local configuration

**Comment by brabo** [comment]
and:

$ rustup update
info: syncing channel updates for 'stable-x86_64-unknown-linux-gnu'
info: checking for self-updates

  stable-x86_64-unknown-linux-gnu unchanged - rustc 1.66.0 (69f9c33d7 2022-12-12)

info: cleaning up downloads & tmp directories

**Comment by Septias** [comment]
solved after dependency updat
